### PR TITLE
Reapplied and fixed #3194

### LINKED ISSUE #3193: [CI] test_tensor_transform unstable after #3184
`Fp16 Hip All Install gfx90a` is unstable after #3184 

Even though CI pipeline for #3184 has a passing history, indeed the test `test_tensor_transform` failed in its first attempt and only passes on the rerun

@atamazov  it is interesting that all the `Mismatch at 0: 3 != 1.5` are exact double, e.g. `Mismatch at 1: 2 != 1` `Mismatch at 4: 4 != 2`

```
[2024-08-10T19:40:00.628Z] /home/jenkins/workspace/MLLIBS_MIOpen_PR-3191/build/bin/test_tensor_transform --half --all --limit 2 --disable-verification-cache 
[2024-08-10T19:40:00.628Z] PRNG seed: 12345678
[2024-08-10T19:40:00.628Z] /home/jenkins/workspace/MLLIBS_MIOpen_PR-3191/build/bin/test_tensor_transform --half --srcLens 32 11 32 16 --scales 0.5 0.5 --superLens_src 32 32 16 16 16 --subLens 16 4 8 1 4 --superLens_dst 32 32 16 16 16 --offset 0 
[2024-08-10T19:40:00.628Z] FAILED: 
[2024-08-10T19:40:00.629Z] Iteration: 54
[2024-08-10T19:40:00.629Z] Tensor Set: {32, 32, 16, 16, 16}, {131072, 4096, 256, 16, 1}, packed, 
[2024-08-10T19:40:00.629Z] super-tensor: 32, 32, 16, 16, 16
[2024-08-10T19:40:00.629Z] sub-tensor: 16, 4, 8, 1, 4
[2024-08-10T19:40:00.629Z] Max diff: 2
[2024-08-10T19:40:00.629Z] Mismatch at 0: 3 != 1.5
```

### PR DESCRIPTION
**Pull request by DrizztDoUrden**
In comparison to #3194 this fixes network config so subsequent invocations with different alpha/beta would not use incorrect kernel binary.
Fixes https://github.com/ROCm/MIOpen/issues/3193

### CODE REVIEW

**Comment by DrizztDoUrden** [comment]
@junliume issue has been marked as blocker, so I have marked this as well. Please correct if I have been wrong

**Review by CAHEK7 — APPROVED** [review]

**Review by junliume — APPROVED** [review]

File: src/ocl/tensorocl.cpp [hunk 1]
```diff
@@ -2308,6 +2309,11 @@ void TransformTensor(const Handle& handle,
             network_config += "x" + std::to_string(len);
         }
 
+        if(is_beta_zero)
+            network_config += "xBETA_IS_ZERO";
+        if(is_alpha_one)
+            network_config += "xALPHA_IS_ONE";
+
```
Comment (atamazov) [inline src/ocl/tensorocl.cpp:2316]: @DrizztDoUrden Thanks for fixing this 🤝 I missed it.

**Review by atamazov — COMMENTED** [review]
🟢 Good!

**Comment by atamazov** [comment]
@junliume The only omission is the name of the PR; I would recommend using the original "[Fix][TransformTensor] Ignore output buffer when BETA=0", possibly with the "2nd attempt" suffix. That would make the life of integration engineer (you) a little bit easier, I guess ;)
