### PR TITLE
Fix batchnorm precision

### LINKED ISSUE #915: [OCL][BatchNorm] Verification failed
The following params of `bnorm` of `bnormfp16` will cause presicion verification failure.
```
MIOpenDriver bnorm -n 38 -c 128 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1 -V 1
MIOpenDriver bnormfp16 -n 38 -c 128 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1 -V 1
MIOpenDriver bnormfp16 -n 38 -c 256 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1 -V 1
MIOpenDriver bnormfp16 -n 38 -c 32 -H 160 -W 160 -m 1 --forw 0 -b 1 -r 1 -V 1
MIOpenDriver bnormfp16 -n 38 -c 512 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1 -V 1
MIOpenDriver bnormfp16 -n 38 -c 64 -H 160 -W 160 -m 1 --forw 0 -b 1 -r 1 -V 1
MIOpenDriver bnormfp16 -n 38 -c 64 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1 -V 1
MIOpenDriver bnormfp16 -n 64 -c 256 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1 -V 1
MIOpenDriver bnormfp16 -n 64 -c 512 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1 -V 1
```

@atamazov UPDATE: More failing configs here: https://github.com/ROCmSoftwarePlatform/MIOpen/pull/916#issuecomment-840199623

### PR DESCRIPTION
**Pull request by zpwenjh**
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/46fbbbf33f96953e98e50d43407dbe29b35de0df/src/ocl/batchnormocl.cpp#L958-L985
In above part，if `in_cstride <= 512 && in_cstride >256 && n < 64`, batchnorm will use `variant = 0` and `xlocalsize = 256`. The corresponding code is as follows:
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/46fbbbf33f96953e98e50d43407dbe29b35de0df/src/kernels/MIOpenBatchNormBwdSpatial.cl#L90
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/46fbbbf33f96953e98e50d43407dbe29b35de0df/src/kernels/MIOpenBatchNormBwdSpatial.cl#L117
The max `lid` is 255, and the memory of `x_in[256]` to `x_in[in_cstride]` will nerver be accessed.

### CODE REVIEW

**Comment by zpwenjh** [comment]
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/46fbbbf33f96953e98e50d43407dbe29b35de0df/src/kernels/MIOpenBatchNormBwdSpatial.cl#L323-L338
This part should read 4 element of `x_in`, if `lid` don't `<< 2`, the code will read same memory repeatedly and the last memory of `x_in` will never be read.

**Comment by atamazov** [comment]
@ce1adon @muralinr please review, thanks.

**Review by muralinr — DISMISSED** [review]
These code changes look good.  Is there any performance impact?  We should mainline these changes even if there is any performance impact.

**Comment by atamazov** [comment]
CI testing job is in progress...

File: driver/bn_driver.hpp [hunk 1]
```diff
@@ -1443,7 +1443,7 @@ int BatchNormDriver<Tgpu, Tref, Tmix>::VerifyBackward()
     dbias_dev->FromGPU(GetStream(), dbias.data());
 #if(MIO_BN_DEBUG == 1)
     const Tref tolerance =
-        static_cast<Tref>(1000 * (sizeof(Tgpu) == 4) ? ERRTOL_FP32 : ERRTOL_FP16);
+        static_cast<Tref>(1000 * ((sizeof(Tgpu) == 4) ? ERRTOL_FP32 : ERRTOL_FP16));
```
Comment (ce1adon) [inline driver/bn_driver.hpp:1446]: Good catch for this one!

File: src/kernels/MIOpenBatchNormBwdSpatial.cl [hunk 2]
```diff
@@ -320,7 +320,7 @@ MIOpenBatchNormBwdSpatial(const __global _FLOAT* __restrict x_in,
 #if(MIO_BN_REM4)
     if(lid < MIO_BN_REM4)
     {
-        unsigned int remkey = lid + MIO_BN_LESS4;
+        unsigned int remkey = (lid << 2) + MIO_BN_LESS4;
```
Comment (ce1adon) [inline src/kernels/MIOpenBatchNormBwdSpatial.cl:323]: This may require a few more subtle changes to avoid overflow within float4 read.

**Comment by atamazov** [comment]
@ce1adon 
> @atamazov @muralinr @zpwenjh
> Can you please review and test the following PR?
> [zpwenjh#14](https://github.com/zpwenjh/MIOpen/pull/14)

Let me just wait for test results from @muralinr.

File: src/ocl/batchnormocl.cpp [hunk 3]
```diff
@@ -976,8 +976,8 @@ void BatchNormBackward(Handle& handle,
                 }
                 else
                 {
-                    xlocalsize = 256;
-                    xgridsize  = 256 * c;
+                    xlocalsize = 512;
+                    xgridsize  = 512 * c;
```
Comment (ce1adon) [inline src/ocl/batchnormocl.cpp:980]: I have concern of this change.
The root cause of the issue is failing to correctly interpret data in float4 type, not the size of the work group.
Enlarging the group size could cover some specific test cases, but will not solve the root issue.

Comment (atamazov) [reply src/ocl/batchnormocl.cpp:980]: @ce1adon Even if so -- is this a good change? Or does it give nothing provided that the root reason is fixed properly?

Comment (ce1adon) [reply src/ocl/batchnormocl.cpp:980]: It gives nothing to fix the root reason.
The only impact is in performance. Will have to wait for @muralinr 's conclusion for this impact.

**Comment by atamazov** [comment]
@zpwenjh We appreciate your efforts but it looks like you do not have enough time to work on this PR.

@ce1adon @muralinr Can we take all good changes from this PR are create a new one, removing the unwanted changes and fixing the root cause of the issue there?

/cc @junliume

File: src/ocl/batchnormocl.cpp (hunk 3 above)
Comment (atamazov) [reply src/ocl/batchnormocl.cpp:980]: @ce1adon Thanks.

**Comment by muralinr** [comment]
> @zpwenjh We appreciate your efforts but it looks like you do not have enough time to work on this PR.
> 
> @ce1adon @muralinr Can we take all good changes from this PR are create a new one, removing the unwanted changes and fixing the root cause of the issue there?
> 
> /cc @junliume

yes Artem. That would be my plan.

**Comment by ce1adon** [comment]
@atamazov I'm investigating this PR as well as issue #915 , and also the comment left by @zpwenjh in https://github.com/zpwenjh/MIOpen/pull/14#discussion_r629792216 . I have concern if these three things have connections or they are actually three different issues. I have made some commits to solve the fp16 issues reported in issue #915 . I observe successful verification in 80x80 and 160x160 cases while 20x20 cases only failed in dscale checking. I doubt the cause is datatype max limits. Still investigating on this one.

**Comment by ce1adon** [comment]
@zpwenjh 
Is the purpose of this PR to fix test cases in issue #915 ? Or you are trying to fix other config failures?

**Comment by zpwenjh** [comment]
> @zpwenjh
> Is the purpose of this PR to fix test cases in issue #915 ? Or you are trying to fix other config failures?

@ce1adon The following configs are also verification failed, and this PR fixed them all.
```sh
./MIOpenDriver bnormfp16 -n 16 -c 1280 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 1280 -H 20 -W 20 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 160 -W 160 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 160 -W 160 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 80 -W 80 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 80 -W 80 
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 80 -W 80 -F 2 -t 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 40 -W 40 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 40 -W 40 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 40 -W 40  -F 4 -t 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 40 -W 40 -F 2 -t 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 80 -W 80 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 80 -W 80 -F 4 -t 1
./MIOpenDriver bnormfp16 -n 16 -c 640 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 640 -H 20 -W 20 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 640 -H 40 -W 40 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 640 -H 40 -W 40 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 80 -H 160 -W 160 -m 1 --forw 0 -b 1 -P 0 -F 4 -t 1
./MIOpenDriver bnormfp16 -n 16 -c 80 -H 160 -W 160 -m 1 --forw 0 -b 1 -F 4 -t 1
./MIOpenDriver bnormfp16 -n 16 -c 80 -H 160 -W 160 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 80 -H 160 -W 160 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 80 -H 160 -W 160 -m 1 --forw 0 -b 1 -r 1 -F 2 -t 1
./MIOpenDriver bnormfp16 -n 16 -c 80 -H 160 -W 160 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 160 -W 160 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 80 -H 160 -W 160 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 40 -W 40 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 80 -H 160 -W 160 -m 1 --forw 0 -b 1 -r 1 -P 0 -F 2 -t 1
./MIOpenDriver bnormfp16 -n 16 -c 80 -H 160 -W 160 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 80 -H 320 -W 320 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 80 -H 320 -W 320 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 1280 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 1280 -H 20 -W 20 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 160 -H 160 -W 160 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 160 -H 160 -W 160 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 160 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 160 -H 80 -W 80 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 320 -H 40 -W 40 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 320 -H 40 -W 40 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 320 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 320 -H 80 -W 80 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 640 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 640 -H 20 -W 20 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 640 -H 40 -W 40 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 640 -H 40 -W 40 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 80 -H 160 -W 160 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 80 -H 160 -W 160 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 80 -H 320 -W 320 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 80 -H 320 -W 320 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 40 -W 40 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 640 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 640 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 640 -H 40 -W 40 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 40 -W 40 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 40 -W 40 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 40 -W 40 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 40 -W 40 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 640 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 640 -H 20 -W 20 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 160 -W 160 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 1280 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 640 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 40 -W 40 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 640 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 40 -W 40 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 640 -H 40 -W 40 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 40 -W 40 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 160 -W 160 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1
```

**Comment by zpwenjh** [comment]
> @zpwenjh
> Is the purpose of this PR to fix test cases in issue #915 ? Or you are trying to fix other config failures?

@ce1adon The following configs are also verification failed, and this PR fixed them all.
```sh
./MIOpenDriver bnormfp16 -n 16 -c 1280 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 1280 -H 20 -W 20 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 160 -W 160 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 160 -W 160 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 80 -W 80 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 80 -W 80 
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 80 -W 80 -F 2 -t 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 40 -W 40 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 40 -W 40 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 40 -W 40  -F 4 -t 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 40 -W 40 -F 2 -t 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 80 -W 80 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 80 -W 80 -F 4 -t 1
./MIOpenDriver bnormfp16 -n 16 -c 640 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 640 -H 20 -W 20 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 640 -H 40 -W 40 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 640 -H 40 -W 40 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 80 -H 160 -W 160 -m 1 --forw 0 -b 1 -P 0 -F 4 -t 1
./MIOpenDriver bnormfp16 -n 16 -c 80 -H 160 -W 160 -m 1 --forw 0 -b 1 -F 4 -t 1
./MIOpenDriver bnormfp16 -n 16 -c 80 -H 160 -W 160 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 80 -H 160 -W 160 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 80 -H 160 -W 160 -m 1 --forw 0 -b 1 -r 1 -F 2 -t 1
./MIOpenDriver bnormfp16 -n 16 -c 80 -H 160 -W 160 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 160 -W 160 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 80 -H 160 -W 160 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 40 -W 40 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 80 -H 160 -W 160 -m 1 --forw 0 -b 1 -r 1 -P 0 -F 2 -t 1
./MIOpenDriver bnormfp16 -n 16 -c 80 -H 160 -W 160 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 80 -H 320 -W 320 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 80 -H 320 -W 320 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 1280 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 1280 -H 20 -W 20 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 160 -H 160 -W 160 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 160 -H 160 -W 160 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 160 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 160 -H 80 -W 80 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 320 -H 40 -W 40 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 320 -H 40 -W 40 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 320 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 320 -H 80 -W 80 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 640 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 640 -H 20 -W 20 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 640 -H 40 -W 40 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 640 -H 40 -W 40 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 80 -H 160 -W 160 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 80 -H 160 -W 160 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 80 -H 320 -W 320 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 4 -c 80 -H 320 -W 320 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 40 -W 40 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 640 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 640 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 640 -H 40 -W 40 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 40 -W 40 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 40 -W 40 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 40 -W 40 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 40 -W 40 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 640 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 640 -H 20 -W 20 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 160 -W 160 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 1280 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 640 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 40 -W 40 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 640 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 40 -W 40 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 640 -H 40 -W 40 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 320 -H 40 -W 40 -m 1 --forw 1 -b 0 -s 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 160 -W 160 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1
./MIOpenDriver bnormfp16 -n 16 -c 160 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1
```

**Comment by ce1adon** [comment]
> > @zpwenjh
> > Is the purpose of this PR to fix test cases in issue #915 ? Or you are trying to fix other config failures?
> 
> @ce1adon The following configs are also verification failed, and this PR fixed them all.
> 

Thank you for the feedback! Notice that all these configures are fp16. In my investigation, I notice that the fp32 types are running OK. 
Meanwhile I notice the output and bias are correct while the failure occurs in scale. 
Will keep updating in this PR.

**Comment by zpwenjh** [comment]
@ce1adon Not all FP32 is ok，I only used FP16 for testing my program. There is a FP32 config that failed to verify too.
```sh
MIOpenDriver bnorm -n 38 -c 128 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1 -V 1
```

**Comment by ce1adon** [comment]
> @ce1adon Not all FP32 is ok，I only used FP16 for testing my program. There is a FP32 config that failed to verify too.
> 
> ```shell
> MIOpenDriver bnorm -n 38 -c 128 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1 -V 1
> ```

This one should be fixed by PR https://github.com/zpwenjh/MIOpen/pull/14

**Comment by ce1adon** [comment]
> @ce1adon The following configs are also verification failed, and this PR fixed them all.
The "-F 4" flag in your cmd should be removed when testing.

**Comment by ce1adon** [comment]
> In above part，if `in_cstride <= 512 && in_cstride >256 && n < 64`, batchnorm will use `variant = 0` and `xlocalsize = 256`. 

@zpwenjh I evaluated your comments. This is true for non-fp32 cases, while fp32 cases will not be affected since the rule to set group size for fp32 and non-fp32 are different. 
@atamazov  @muralinr  We need a solution involving either group size or layout change, which will affect performance anyway. Please keep us updated about the performance test.

**Comment by muralinr** [comment]
> > In above part，if `in_cstride <= 512 && in_cstride >256 && n < 64`, batchnorm will use `variant = 0` and `xlocalsize = 256`.
> 
> @zpwenjh I evaluated your comments. This is true for non-fp32 cases through variant 0 path, while fp32 cases and other non-fp32 paths will not be affected since the rule to set group size for them are different. However, the cases of fp16 through variant 0 do fail due to current layout rules. Thanks for catching it!
> The problem of fp32 and the other non-fp32 path is due to fail to accumulate float4 residual data properly. A fix is done in [zpwenjh#14](https://github.com/zpwenjh/MIOpen/pull/14) . Please check.
> 
> @atamazov @muralinr We need a solution involving either group size or layout change, which will affect performance anyway. Please keep us updated about the performance test.

Do we have final code ready for both PRs to evaluate performance?

**Comment by atamazov** [comment]
@ce1don In other words, please update @muralinr with repository name, branch name and git hash that you would like to test BN performance of.

@muralinr AFAICS the current baseline for performance testing of this PR is `develop` 46fbbbf33 (see https://github.com/zpwenjh/MIOpen/commits/fix_batchnorm_precision)

**Comment by muralinr** [comment]
> @ce1don In other words, please update @muralinr with repository name, branch name and git hash that you would like to test BN performance of.
> 
> @muralinr AFAICS the current baseline for performance testing of this PR is `develop` [46fbbbf](https://github.com/ROCmSoftwarePlatform/MIOpen/commit/46fbbbf33f96953e98e50d43407dbe29b35de0df) (see https://github.com/zpwenjh/MIOpen/commits/fix_batchnorm_precision)

@ce1don Can you please let me know once PR is ready for performance testing..

**Comment by ce1adon** [comment]
> > @ce1don In other words, please update @muralinr with repository name, branch name and git hash that you would like to test BN performance of.
> > @muralinr AFAICS the current baseline for performance testing of this PR is `develop` [46fbbbf](https://github.com/ROCmSoftwarePlatform/MIOpen/commit/46fbbbf33f96953e98e50d43407dbe29b35de0df) (see https://github.com/zpwenjh/MIOpen/commits/fix_batchnorm_precision)
> 
> @ce1don Can you please let me know once PR is ready for performance testing..

Sure. Will let you know @muralinr

**Comment by ce1adon** [comment]
@atamazov @muralinr @zpwenjh   After re-examining the non-fp32 variant 0 path, I believe @zpwenjh 's proposal of enlarge the group size for non-fp32 case will have the minimum impact on performance. I reverted this change in https://github.com/zpwenjh/MIOpen/pull/14. Now https://github.com/zpwenjh/MIOpen/pull/14 should have everything fix reported issues in both #916 and #915 . @zpwenjh Thank you for your contribution in this topic!
@muralinr Please go ahead to pull changes in https://github.com/zpwenjh/MIOpen/pull/14 for a performance test. Thank you!

**Comment by atamazov** [comment]
@zpwenjh Yes, thanks again for your contribution! Could you please merge the recent develop to `zpwenjh:fix_batchnorm_precision`? I do not have access. 

Then we'll compare performance of this PR with develop, make sure the PR pass CI, and finally, merge this to develop. Thanks!

/cc @muralinr

**Comment by zpwenjh** [comment]
> @zpwenjh Yes, thanks again for your contribution! Could you please merge the recent develop to `zpwenjh:fix_batchnorm_precision`? I do not have access.
> 
> Then we'll compare performance of this PR with develop, make sure the PR pass CI, and finally, merge this to develop. Thanks!
> 
> /cc @muralinr

@atamazov This develop branch is now merged to this PR.

**Comment by muralinr** [comment]
> > @zpwenjh Yes, thanks again for your contribution! Could you please merge the recent develop to `zpwenjh:fix_batchnorm_precision`? I do not have access.
> > Then we'll compare performance of this PR with develop, make sure the PR pass CI, and finally, merge this to develop. Thanks!
> > /cc @muralinr
> 
> @atamazov This develop branch is now merged to this PR.

I started running verification and performance tests.  I will update results this week.

**Comment by muralinr** [comment]
> > > @zpwenjh Yes, thanks again for your contribution! Could you please merge the recent develop to `zpwenjh:fix_batchnorm_precision`? I do not have access.
> > > Then we'll compare performance of this PR with develop, make sure the PR pass CI, and finally, merge this to develop. Thanks!
> > > /cc @muralinr
> > 
> > 
> > @atamazov This develop branch is now merged to this PR.
> 
> I started running verification and performance tests. I will update results this week.

Both BN forward and backward verification and performance tests are fine.  We can go ahead with this PR.

**Comment by atamazov** [comment]
@ce1adon Do you approve?

**Review by atamazov — APPROVED** [review]
I do not see anything bad.

**Review by ce1adon — APPROVED** [review]

**Comment by atamazov** [comment]
@zpwenjh @ce1adon @muralinr 
## :tada:

File: src/ocl/batchnormocl.cpp (hunk 3 above)
Comment (ce1adon) [reply src/ocl/batchnormocl.cpp:980]: @atamazov Please note that enlarge the group size could lead to summation overflow in fp16, regarding to the issue you are working on.
