### PR TITLE
Exclude squashed tensorop

### LINKED ISSUE #2316: Op2dTensorSquash doesn't fit into tensor operation paradigm and can't pass the tests.
@muralinr @zjing14 probably you may shed some light on it.
@junliume probably you know who else worked on this code and may answer the questions.

Should we move Op2dTensorSquash outside of 3d tensors operations and add separated tests and all the infrastructure for it? Combining different functionality under one API interface seems error prone for me.

Here is a detail description:

For 3d tensor operations there is a special `Squash` case where tensor B is not equal to A and C and is not properly squashed.
It supposed to be either equal to A and C A:2x3x4 and B:2x3x4 or some of the dimensions are squashed like B:1x3x4 or B:1x1x4 or B:2x3x1 but for that particular `squashed` case there is an exception https://github.com/ROCmSoftwarePlatform/MIOpen/blob/a0c73f544d3db86511f8a521a34198cba5939ac7/src/ocl/tensorocl.cpp#L1286 which explicitly breaks the rule and allows following combinations: A:1x1x3 and B:1x100x3.

The problem is `Op2dTensorSquash` does not pass tensor_ops tests but it is used in RNN tests and RNN relies on its behavior (when I force to use any non-squashed version which pass tensot_ops tests, it fails RNN tests):
<details>
<summary>Failed log</summary>
```
./bin/test_tensor_ops --float --a 1 1 3 --b 1 3 3 --offsets 0 0 0 --alpha-beta 1 1 1 --packed 1 --sa 1 1 1 --sb 1 1 1 --sc 1 1 1
...
MIOpen(HIP): Info2 [GetKernels] 0 kernels for key: Op2dTensorSquash "1-1-1-1x256x1"                                                              [2296/9067]MIOpen(HIP): Info2 [AddKernel] Key: Op2dTensorSquash "1-1-1-1x256x1"                                                                                        MIOpen(HIP): Info [PrintVersionImpl] COMgr v.2.5.0, USE_HIP_PCH: 1                                                                                          MIOpen(HIP): Info2 [SetIsaName] amdgcn-amd-amdhsa--gfx1030                                                                                                  MIOpen(HIP): Info2 [Log] Kernel MIOpenTensorKernels.cl Compile Time, ms: 223.932                                                                            MIOpen(HIP): Info2 [run] kernel_name = Op2dTensorSquash, global_work_dim = { 256, 1, 1 }, local_work_dim = { 256, 1, 1 }                                    GPU_C[0]: 57.000000                                                                                                                                         GPU_C[1]: 217.000000
GPU_C[2]: 286.000000
GPU_A[0]: 3.000000
GPU_A[1]: 7.000000
GPU_A[2]: 11.000000
GPU_B[0]: 3.000000
GPU_B[1]: 7.000000
GPU_B[2]: 11.000000
GPU_B[3]: 6.000000
GPU_B[4]: 10.000000
GPU_B[5]: 14.000000
GPU_B[6]: 9.000000
GPU_B[7]: 13.000000
GPU_B[8]: 0.000000
MIOpen(HIP): Info2 [default_deallocator] hipFree 36 at 0x7fc19fc02000 Ok
MIOpen(HIP): Info2 [default_deallocator] hipFree 12 at 0x7fc19fc01000 Ok
MIOpen(HIP): Info2 [default_deallocator] hipFree 12 at 0x7fc19fc00000 Ok
c[0](3.000000) = a[0](3.000000) * b[0](3.000000)
c[1](7.000000) = a[1](7.000000) * b[1](7.000000)
c[2](11.000000) = a[2](11.000000) * b[2](11.000000)
CPU_C[0]: 12.000000
CPU_C[1]: 56.000000
CPU_C[2]: 132.000000
./bin/test_tensor_ops --float --a 1 1 3 --b 1 3 3 --sa 1 1 1 --sb 1 1 1 --sc 1 1 1 --offsets 0 0 0 --alpha-beta 1 1 1 --packed 1
FAILED: 0.458838
Iteration: 0
TensorOp:
A tensor: 1, 1, 3
B tensor: 1, 3, 3
C tensor: 1, 1, 3
Offsets: 0,0,0
Max diff: 161
Mismatch at 0: 12 != 57
```
</details>

Currently to run such tests the check at https://github.com/ROCmSoftwarePlatform/MIOpen/blob/a0c73f544d3db86511f8a521a34198cba5939ac7/test/tensor_ops.cpp#L317 should be disabled, since it verifies normal tensor operations requirements and `squashed` version is out of this scope.

### PR DESCRIPTION
**Pull request by CAHEK7**
As described in #2316, squashed tensor ops do ne behave like a normal tensor operation and should not be exposed to the external API. Previously it has been done for offsets - they are not a part of external API and thus hidden.

This PR enables this non-standard behavior only for some RNN cases, where it's required and for what it has been invented.
RNN tests from #2316/#2318 and smoke tests have passed successfully.

Blocked by #2318 

Closes #2316

### CODE REVIEW

File: src/kernels/MIOpenTensorKernelsHip.cpp [hunk 1]
```diff
@@ -65,9 +65,9 @@ extern "C" __global__ void Op1dTensorGeneric(const MIOPEN_TYPE* __restrict__ a,
                                              const uint32_t total_work,
                                              const bool use_beta)
 {
-    const MIOPEN_TYPE* __restrict__ a_off = a + Aoffset;
-    const MIOPEN_TYPE* __restrict__ b_off = b + Boffset;
-    MIOPEN_TYPE* __restrict__ c_off       = c + Coffset;
+    const MIOPEN_TYPE* a_off = a + Aoffset;
```
Comment (muralinr) [inline src/kernels/MIOpenTensorKernelsHip.cpp:68]: Why __restrict__ qualifier is removed? This allows the compiler to make optimizations (for example, vectorization) that would not otherwise have been possible.

**Comment by muralinr** [comment]
Can you please run these below RNN tests too?
 
./bin/MIOpenDriver rnnfp16 -n 224 -W 224 -H 1000 -l 8 -b 1 -m lstm -p 0 -r 0 -k 32 -F 4 -t 1 -w 1
./bin/MIOpenDriver rnnfp16 -n 224 -W 224 -H 1000 -l 8 -b 1 -m lstm -p 0 -r 0 -k 32 -c 0 -F 1 -t 1 -w 1

File: src/kernels/MIOpenTensorKernelsHip.cpp (hunk 1 above)
Comment (CAHEK7) [reply src/kernels/MIOpenTensorKernelsHip.cpp:68]: I'm aware about it.
I removed `__restrict__` because it assumes that pointers do not overlap, but as far as I can see - we can't guarantee that, so the optimizations may not be applicable.

Here is an example: https://github.com/ROCmSoftwarePlatform/MIOpen/blob/38318373d6bf2492af99d9e65bfdf7815945d3c9/src/convolution_api.cpp#L752

It passes the same tensor to A and C with the same 0 offset - they will definitely overlap. Moreover it's a part of extranal API.

**Comment by CAHEK7** [comment]
> Can you please run these below RNN tests too?
> 
> ./bin/MIOpenDriver rnnfp16 -n 224 -W 224 -H 1000 -l 8 -b 1 -m lstm -p 0 -r 0 -k 32 -F 4 -t 1 -w 1
> ./bin/MIOpenDriver rnnfp16 -n 224 -W 224 -H 1000 -l 8 -b 1 -m lstm -p 0 -r 0 -k 32 -c 0 -F 1 -t 1 -w 1

@muralinr, it's already done - it's exactly the same test from #2316 and #2318. It passes.

**Comment by muralinr** [comment]
> > Can you please run these below RNN tests too?
> > ./bin/MIOpenDriver rnnfp16 -n 224 -W 224 -H 1000 -l 8 -b 1 -m lstm -p 0 -r 0 -k 32 -F 4 -t 1 -w 1
> > ./bin/MIOpenDriver rnnfp16 -n 224 -W 224 -H 1000 -l 8 -b 1 -m lstm -p 0 -r 0 -k 32 -c 0 -F 1 -t 1 -w 1
> 
> @muralinr, it's already done - it's exactly the same test from #2316 and #2318. It passes.

Good. Thanks for confirmation.

File: src/kernels/MIOpenTensorKernelsHip.cpp (hunk 1 above)
Comment (muralinr) [reply src/kernels/MIOpenTensorKernelsHip.cpp:68]: Ok. It's fine to remove restrict qualifier to pointer if we can't guarantee no other pointer will be used to access the memory to which it points.

**Comment by junliume** [comment]
@CAHEK7 please help to resolve the conflicts by merging the latest `develop` branch into your feature branch. Thanks!

**Comment by junliume** [comment]
@muralinr @JehandadKhan ping for review after CI passing.

File: src/kernels/MIOpenTensorKernelsHip.cpp [hunk 2]
```diff
@@ -50,9 +50,9 @@ __device__ T miopenMin(T a, T b)
 
 #ifdef USE_1D_TENSOR_GENERIC
 // N
-extern "C" __global__ void Op1dTensorGeneric(const MIOPEN_TYPE* __restrict__ a,
-                                             const MIOPEN_TYPE* __restrict__ b,
-                                             MIOPEN_TYPE* __restrict__ c,
+extern "C" __global__ void Op1dTensorGeneric(const MIOPEN_TYPE* a,
```
Comment (JehandadKhan) [inline src/kernels/MIOpenTensorKernelsHip.cpp:53]: @CAHEK7 Good catch!

**Review by JehandadKhan — APPROVED** [review]

**Comment by JehandadKhan** [comment]
@junliume  This can be merged!

**Review by junliume — APPROVED** [review]
