### PR TITLE
[pooling][backward][2D] Support wide pooling window. Fix FP16 correctness issues of Average pooling.

### LINKED ISSUE #2344: [pooling][average][FP16] PoolingBackwardNd: Correctness problems with big tensors
Tested on Navi21 and gfx906/60, ROCm 5.4 and 5.7 RC. The problem is inherent to averaging modes only, similar to #2109. Most likely, the reason is that computations are performed in FP16 domain which leads to overflow when the number of FP ops is big.

Examples:

```bash
./bin/test_pooling3d --half --index_type miopenIndexUint32 --mode miopenPoolingAverage --verify_indices 1 --input 1 64 1 410 400 --lens 1 409 399 --strides 1 1 1 --pads 0 0 0 --wsidx 0 -F 1 --disable-verification-cache -v
FAILED: 0.721753
Max diff: 0.0429382
Gpu data is all zeros
Mismatch at 0: 0.00105953 != 0
Backward Pooling: Average
Lengths: 1, 409, 399
Pads: 0, 0, 0
Strides: 1, 1, 1
Input tensor: 1, 64, 1, 410, 400
Output tensor: 1, 64, 1, 2, 2
```

```bash
./bin/test_pooling3d --half --index_type miopenIndexUint32 --mode miopenPoolingAverage --verify_indices 1 --input 1 64 11 41 400 --lens 10 40 399 --strides 1 1 1 --pads 0 0 0 --wsidx 0 -F 1 --disable-verification-cache -v
...
FAILED: 0.734635
Max diff: 0.0778198
Gpu data is all zeros
Mismatch at 0: 0.00108337 != 0
Backward Pooling: Average
Lengths: 10, 40, 399
Pads: 0, 0, 0
Strides: 1, 1, 1
Input tensor: 1, 64, 11, 41, 400
Output tensor: 1, 64, 2, 2, 2
```

```bash
./bin/test_pooling3d --half --index_type miopenIndexUint32 --mode miopenPoolingAverageInclusive --verify_indices 1 --wsidx 1 --input 1 3 1 256 256 --lens 1 180 180 --strides 1 1 1 --pads 0 0 0 --disable-verification-cache -v
...
FAILED: 0.255373
Max diff: 80.5
Mismatch at 0: 0.00533676 != 0.00534058
Backward Pooling: AverageInclusive
Lengths: 1, 180, 180
Pads: 0, 0, 0
Strides: 1, 1, 1
Input tensor: 1, 3, 1, 256, 256
Output tensor: 1, 3, 1, 77, 77
```

----
[Attribution] @junliume @JehandadKhan
- https://github.com/ROCmSoftwarePlatform/MIOpen/labels/bug
- https://github.com/ROCmSoftwarePlatform/MIOpen/labels/urgency_blocker
- Proposed assignees: @atamazov 
  - Actually I am fixing this altogether with implementing backward pooling support for big tensors, because this bug blocks my work.

### PR DESCRIPTION
**Pull request by atamazov**
This PR contains some fixes and enhancements for pooling. Main products: Resolves (2) from #2110, resolves #2344. Leftover to reach full support for wide pooling window:
- #2371

## Details
- Fixes:
  - 🔴 PoolingBackward2d and PoolingBackwardNd: In averaging modes, use mixed-precision computation to fix correctness issues. Partially resolves [#2344](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/2344)
  - 🟡 Fixed workspace index range check: do not allow to reach max value in Max pooling mode.
- Enhancements:
  - 🔴 PoolingBackwardNd: Adapted for 2D problems. Removed redundant computations from Invoker. Resolves (2) from [#2110](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/2110)  (AP 1.2 at [proposal](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/2110#issuecomment-1518743692)).
- Optimizations:
  - PoolingBackwardNd: optimize binary size and kernel build time
- Code quality fixes:
  - Explicitly declare that only Direct pooling algorithm is implemented so far.
  - float_types.h: Introduce `CVT_INTEGRAL2ACCUM` and `MIOPEN_USE_DOUBLE_ACCUM`, refactor code.
  - Improve comments and diagnostic messages
  - Make PoolingForwardNaive applicable only for the supported pooling ops.
  - Move check for index mask mode into respective solvers.
- Pooling tests:
  - 🔴 Fix: Generate reference data in double domain. Partially resolves [#2344](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/2344).
  - 🟠 Enhancement: Added full test for 2D wide pooling configs.
  - Optimizations
    - Optimized all datasets by skipping "wsidx 0" in average pooling modes.
    - Optimized asymmetric dataset by limiting it to 8-and 32-bit indices.
    - Removed 2D driver-based regression tests (issues 2109, 2110) as these now included into wide dataset.
  - Quality/usability fixes:
    - Issue an informative warning if some test config is skipped.
    - Added some more explicit skips. Do not use the most of the skips unless the Full tests mode ("--all") is used.
    - Removed redundant config check.
- Pooling driver fixes:
  - If pooling fails, print zero GPU time and pass the error code to the caller. This makes driver's output more correct.
  - Initialize output buffer with a non-zero value to make validation errors always visible when the kernel isn't run (important for average pooling).

## 🌀 Testing info

Manually tested on Navi21 and Radeon VII, both FP32 and FP16 pooling tests - all pass.

----
[Attribution] @junliume
- https://github.com/ROCmSoftwarePlatform/MIOpen/labels/enhancement
- https://github.com/ROCmSoftwarePlatform/MIOpen/labels/bug
- https://github.com/ROCmSoftwarePlatform/MIOpen/labels/correctness
- https://github.com/ROCmSoftwarePlatform/MIOpen/labels/urgency_blocker
- Proposed reviewers:
  - @JehandadKhan
  - @zjing14

### CODE REVIEW

**Comment by junliume** [comment]
@atamazov we have met some HIP tidy issues, you can reproduce using non-GPU platform:
```
[2023-09-05T16:01:27.151Z] /var/jenkins/workspace/MLLibs_MIOpen_PR-2372/test/pooling_common.hpp:62:1: error: do not use unnamed namespaces in header files [cert-dcl59-cpp,google-build-namespaces,-warnings-as-errors]

[2023-09-05T16:01:27.151Z] namespace {

[2023-09-05T16:01:27.151Z] ^

[2023-09-05T16:01:27.151Z] /var/jenkins/workspace/MLLibs_MIOpen_PR-2372/test/pooling_common.hpp:64:6: error: function 'print' defined in a header file; function definitions in header files can lead to ODR violations [misc-definitions-in-headers,-warnings-as-errors]

[2023-09-05T16:01:27.151Z] void print(const miopen::PoolingDescriptor& filter)

[2023-09-05T16:01:27.151Z]      ^
[2023-09-05T16:01:27.151Z] /var/jenkins/workspace/MLLibs_MIOpen_PR-2372/test/pooling_common.hpp:371:52: error: result of integer division used in a floating point context; possible loss of precision [bugprone-integer-division,-warnings-as-errors]

[2023-09-05T16:01:27.151Z]                             din_vec.at(din_idx) += dout(o, w, out_spatial_id_pack...) / pool_size;

[2023-09-05T16:01:27.151Z]                                                    ^
```

**Comment by atamazov** [comment]
@junliume Thank you. It shall pass now, can you please start another CI round? 🤝

File: driver/pool_driver.hpp [hunk 1]
```diff
@@ -455,25 +455,27 @@ int PoolDriver_impl<Tgpu, Tref, Index>::RunForwardGPU()
...
-                             &alpha,
-                             inputTensor,
-                             in_dev->GetMem(),
-                             &beta,
-                             outputTensor,
-                             out_dev->GetMem(),
-                             do_backward,
-                             mask_dev->GetMem(),
-                             0);
+        rc |= miopenPoolingForward(GetHandle(),
```
Comment (CAHEK7) [inline driver/pool_driver.hpp:463]: I hope in case of error it will return exactly the same `miopenStatus_t` value for all the iteration.
Otherwise returning combined value may lead to bogus status reporting (if someone decided to parse the status)

File: driver/pool_driver.hpp [hunk 2]
```diff
@@ -455,25 +455,27 @@ int PoolDriver_impl<Tgpu, Tref, Index>::RunForwardGPU()
...
+                                   out_dev->GetMem(),
+                                   do_backward,
+                                   mask_dev->GetMem(),
+                                   0);
     }
     if(inflags.GetValueInt("time") == 1)
     {
         float time = 0.0;
-        miopenGetKernelTime(GetHandle(), &time);
+        if(rc == 0)
```
Comment (CAHEK7) [inline driver/pool_driver.hpp:478]:
```suggestion
        if(rc == miopenStatusSuccess)
```

File: driver/pool_driver.hpp [hunk 3]
```diff
@@ -455,25 +455,27 @@ int PoolDriver_impl<Tgpu, Tref, Index>::RunForwardGPU()
 
     Timer t;
     START_TIME
+    int rc = 0;
```
Comment (CAHEK7) [inline driver/pool_driver.hpp:459]:
```suggestion
    static_assert(miopenStatusSuccess == 0);
    int rc = miopenStatusSuccess;
```
Otherwise bitwise OR logic is broken.

File: driver/pool_driver.hpp [hunk 4]
```diff
@@ -523,27 +525,29 @@ int PoolDriver_impl<Tgpu, Tref, Index>::RunBackwardGPU()
...
```
Comment (CAHEK7) [inline driver/pool_driver.hpp:529]: The same as previous comment.

File: src/solver/pooling/backwardNd.cpp [hunk 5]
```diff
@@ -54,165 +69,180 @@ PoolingBackwardNd::GetSolution(const ExecutionContext&,
...
+            problem.GetPooling().GetMode() == miopenPoolingAverageInclusive)
     {
-        auto kernel = KernelInfo{};
+        kernel.kernel_name += "AveBwd";
+    }
 
-        kernel.kernel_file = "MIOpenPoolingBwdND.cl";
-        kernel.kernel_name = "mloPoolingND";
+    const auto bot = problem.GetXDesc();
+    const auto top = problem.GetYDesc();
```
Comment (CAHEK7) [inline src/solver/pooling/backwardNd.cpp]:
```suggestion
    const auto& bot = problem.GetXDesc();
    const auto& top = problem.GetYDesc();
```
Shall it be a reference to avoid extra copy?

File: src/solver/pooling/backwardNd.cpp [hunk 6]
```diff
@@ -54,165 +69,180 @@ PoolingBackwardNd::GetSolution(const ExecutionContext&,
...
-            int bot_h = *(params.dxDesc.GetLengths().rbegin() + 1);
-            int bot_w = *(params.dxDesc.GetLengths().rbegin());
+    const auto top_d = is2d ? 1 : *(top.GetLengths().rbegin() + 2);
+    const auto top_h = *(top.GetLengths().rbegin() + 1);
+    const auto top_w = *(top.GetLengths().rbegin());
 
-            int pix_blk_w = std::max((bot_w + pix_w_per_work - 1) / pix_w_per_work, 1);
-            int pix_blk_h = std::max((bot_h + pix_h_per_work - 1) / pix_h_per_work, 1);
-            int pix_blk_d = std::max((bot_d + pix_d_per_work - 1) / pix_d_per_work, 1);
+    const auto bot_strides  = bot.GetStrides();
```
Comment (CAHEK7) [inline src/solver/pooling/backwardNd.cpp]:
```suggestion
    const auto& bot_strides  = bot.GetStrides();
```

File: src/solver/pooling/backwardNd.cpp [hunk 7]
```diff
@@ -54,165 +69,180 @@ PoolingBackwardNd::GetSolution(const ExecutionContext&,
...
+    const auto bot_n_stride = bot_strides[0];
+    const auto bot_c_stride = bot_strides[1];
+    const auto bot_d_stride = bot_strides[2]; // Same as bot_h_stride in 3D converted from 2D.
+    const auto bot_h_stride = is2d ? bot_strides[2] : bot_strides[3];
+    const auto top_strides  = top.GetStrides();
```
Comment (CAHEK7) [inline src/solver/pooling/backwardNd.cpp]:
```suggestion
    const auto& top_strides  = top.GetStrides();
```

File: src/solver/pooling/backwardNd.cpp [hunk 8]
```diff
@@ -54,165 +69,180 @@ PoolingBackwardNd::GetSolution(const ExecutionContext&,
...
+    const auto top_n_stride = top_strides[0];
+    const auto top_c_stride = top_strides[1];
+    const auto top_d_stride = top_strides[2]; // Same as top_h_stride in 3D converted from 2D.
+    const auto top_h_stride = is2d ? top_strides[2] : top_strides[3];
```
Comment (CAHEK7) [inline src/solver/pooling/backwardNd.cpp]:
```C++
auto unpackStrides = [is2d](const auto& strides)
{
    return std::make_tuple(strides[0], strides[1], strides[2], // Same as...
                           is2d ? strides[2] : strides[3]);
};

auto [bot_n_stride, bot_c_stride, bot_d_stride, bot_h_stride] = unpackStrides(bot.GetStrides());
auto [top_n_stride, top_c_stride, top_d_stride, top_h_stride] = unpackStrides(top.GetStrides());
```
What do you think?

**Review by CAHEK7 — COMMENTED** [review]
Some minor changes to avoid extra std::vector copy.

**Comment by junliume** [comment]
@atamazov I think there is no objections except a few polishing comments, could you revise the PR adopting some of the recommendations? I will merge it afterwards. Thanks!

File: driver/pool_driver.hpp (hunk 1 above)
Comment (atamazov) [reply driver/pool_driver.hpp:463]: Sure, this is a hack, but I hope this is acceptable for now for the driver.

File: driver/pool_driver.hpp (hunk 3 above)
Comment (atamazov) [reply driver/pool_driver.hpp:459]: `miopenStatusSuccess == 0` is carved in stone (in the public API) and should never change. Let me keep 0 for the sake of the old-style hackery.

File: src/solver/pooling/backwardNd.cpp (hunk 8 above)
Comment (atamazov) [reply src/solver/pooling/backwardNd.cpp]: I would prefer the variant which is easier to read. Which one is easier for you? just tell me and I'll follow ;)

File: src/solver/pooling/backwardNd.cpp (hunk 5 above)
Comment (atamazov) [reply src/solver/pooling/backwardNd.cpp]: (Let me check tomorrow)

File: src/solver/pooling/backwardNd.cpp (hunk 8 above)
Comment (CAHEK7) [reply src/solver/pooling/backwardNd.cpp]: Probably initial version may be a bit easier to read, but it generates a lot of identical copy-pasted code and can be error-prone.
In case of lambda it explicitly states that strides layouts are identical, and it can be modified in an easier and safer way, so you won't miss one index somewhere or get `top` strides from `bot` tensor (except the case where strides layout becomes different and everything will be split anyways).

Also I'd preferred explicit naming for operations.

Comment (atamazov) [reply src/solver/pooling/backwardNd.cpp]: This leads to `error: reference to local binding 'bot_n_stride' declared in enclosing function 'miopen::solver::pooling::PoolingBackwardNd::GetSolution'`, see https://stackoverflow.com/questions/46114214/lambda-implicit-capture-fails-with-variable-declared-from-structured-binding

Comment (atamazov) [reply src/solver/pooling/backwardNd.cpp]: I am going to use std::tie. The constness is lost.

File: driver/pool_driver.hpp (hunk 2 above)
Comment (atamazov) [reply driver/pool_driver.hpp:478]: [resolved as previous]

File: driver/pool_driver.hpp (hunk 4 above)
Comment (atamazov) [reply driver/pool_driver.hpp:529]: [resolved as previous]

File: src/solver/pooling/backwardNd.cpp (hunk 5 above)
Comment (atamazov) [reply src/solver/pooling/backwardNd.cpp]: [resolved]

File: src/solver/pooling/backwardNd.cpp (hunk 6 above)
Comment (atamazov) [reply src/solver/pooling/backwardNd.cpp]: [not relevant anymore]

File: src/solver/pooling/backwardNd.cpp (hunk 7 above)
Comment (atamazov) [reply src/solver/pooling/backwardNd.cpp]: [not relevant anymore]

File: src/solver/pooling/backwardNd.cpp (hunk 8 above)
Comment (atamazov) [reply src/solver/pooling/backwardNd.cpp]: @CAHEK7 I recommend looking at the result at 8be604cca0b503d9eeb6a06a710aa0f900401d3f
[resolved]

**Comment by atamazov** [comment]
@junliume @CAHEK7 PR is ready for the next review & CI testing round.

**Review by CAHEK7 — APPROVED** [review]

File: src/solver/pooling/backwardNd.cpp (hunk 8 above)
Comment (CAHEK7) [reply src/solver/pooling/backwardNd.cpp]: > @CAHEK7 I recommend looking at the result at [8be604c](https://github.com/ROCmSoftwarePlatform/MIOpen/commit/8be604cca0b503d9eeb6a06a710aa0f900401d3f) [resolved]

@atamazov , I agree it looks ugly (

As about the constness it does not matter in this particular context, because later it captured by value and constness can be guaranteed since invoker lambda is non-mutable (or will be lost anyway, if lambda is mutable).

Comment (atamazov) [reply src/solver/pooling/backwardNd.cpp]: [Notice] Possibility of constness can be used as a criterion of good design. If the design does not allow creating const entities wherever those entities can not change, then the design well... er... may be improved.
