### PR TITLE
[OCL][MI100][MI200] Fix iGemm ASM GTC XDLOPS failures with OCL backend (Staging 95b58f72f) (#1317) and Implement abstraction for multi-buffer workspace (#1326) 

### LINKED ISSUE #1317: [OCL][MI100][MI200] iGemm ASM GTC XDLOPS failures with OCL backend (Staging 95b58f72f)
`make check` convolution failures. Preconditions:
- Mainline build 9148
- OpenCL backend
- NCHW configs
- MI200 (possibly MI100 as well -- not tested)

:warning: GPU is dead after the failure (`sudo cat /sys/kernel/debug/dri/<GPU_NUM>/amdgpu_gpu_recover` to recover).

```
../bin/test_conv2d --float --cmode conv --pmode default --group-count 3 --input 16 9 224 224 --weights 63 3 3 3 --batch_size 16 --input_channels 9 --output_channels 63 --spatial_dim_elements 224 224 --filter_dims 3 3 --pads_strides_dilations 1 1 1 1 1 1 --trans_output_pads 0 0 --in_layout NCHW --fil_layout NCHW --out_layout NCHW
MIOpen(OpenCL): Info [ForwardGetWorkSpaceSize]
MIOpen(OpenCL): Info [GetForwardSolutions]
MIOpen(OpenCL): Info [HeuristicInit] 32,256,4,32,64,4,16,64,16,0,1,8
MIOpen(OpenCL): Info [FindConvFwdAlgorithm] requestAlgoCount = 1, workspace = 231217812
MIOpen(OpenCL): Info [GetForwardSolutions]
MIOpen(OpenCL): Info [TryLoad] Find-db regenerating.
MIOpen(OpenCL): Info [FindSolutionImpl] ConvBinWinogradRxSf3x2
MIOpen(OpenCL): Info [FindSolutionImpl] Perf Db: record not found for: ConvBinWinogradRxSf3x2
MIOpen(OpenCL): Info [GetPerformanceConfig] 34
MIOpen(OpenCL): Info [FindSolutionImpl] ConvBinWinogradRxSf2x3
MIOpen(OpenCL): Info [FindSolutionImpl] Perf Db: record not found for: ConvBinWinogradRxSf2x3
MIOpen(OpenCL): Info [GetPerformanceConfig] 34
MIOpen(OpenCL): Info [FindSolutionImpl] GemmFwdRest (not searchable)
MIOpen(OpenCL): Info [FindSolutionImpl] ConvDirectNaiveConvFwd (not searchable)
MIOpen(OpenCL): Info [FindSolutionImpl] ConvAsmImplicitGemmGTCDynamicFwdXdlopsNHWC
MIOpen(OpenCL): Info [FindSolutionImpl] Perf Db: record not found for: ConvAsmImplicitGemmGTCDynamicFwdXdlopsNHWC
MIOpen(OpenCL): Info [GetPerformanceConfig] fwd,nhwc,fp32,0,1,256,32,4,64,32,1,1,1,2,1,0,0,0,1,0,1,1,8,1,1,4,1,32,1,1,1,1,1,4,1,32,0
MIOpen(OpenCL): Info [KernDb] database not present
MIOpen(OpenCL): Info [EvaluateInvokers] GemmFwdRest: : 1.9328 < 3.40282e+38
MIOpen(OpenCL): Info [EvaluateInvokers] Selected: GemmFwdRest: : 1.9328, workspce_sz = 16257024
MIOpen(OpenCL): Info [EvaluateInvokers] ConvBinWinogradRxSf3x2: miopenSp3AsmConv_v21_1_3_gfx9_f3x2_fp32_stride1_group: 0.650397 < 3.40282e+38
MIOpen(OpenCL): Info [EvaluateInvokers] ConvBinWinogradRxSf2x3: miopenSp3AsmConv_v21_1_3_gfx9_fp32_stride1_group: 0.650557 >= 0.650397
MIOpen(OpenCL): Info [EvaluateInvokers] Selected: ConvBinWinogradRxSf3x2: miopenSp3AsmConv_v21_1_3_gfx9_f3x2_fp32_stride1_group: 0.650397, workspce_sz = 0
MIOpen(OpenCL): Info [EvaluateInvokers] ConvDirectNaiveConvFwd: naive_conv_fwd_nchw_fp32: 4.04575 < 3.40282e+38
MIOpen(OpenCL): Info [EvaluateInvokers] Selected: ConvDirectNaiveConvFwd: naive_conv_fwd_nchw_fp32: 4.04575, workspce_sz = 0
Memory access fault by GPU node-13 (Agent handle: 0x560e10614d00) on address 0xbc3b723000. Reason: Unknown.
```

The memory access fault happens when some `igemm_fwd_gtcx2_*` is running, please see attached log: [issue-16-9-224-224.opencl.ll6.dev-debug.nogemm.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/7654756/issue-16-9-224-224.opencl.ll6.dev-debug.nogemm.txt).

### LINKED ISSUE #1326: Implement and use an abstraction that represents a multi-buffer workspace
This seems Ok as a hotfix. However we should hide details in some suitable abstraction instead hacky code here and there. In this specific case, I can propose some class that can represents metrics of a workspace that logically consists of two sub-buffers, each with its own size and alignment. Very basic example:
```C++
WorkspaceBuf2Traits wt(size_0, size_1, alignment_1);
...
wt.GetSize(); // total workspace size
wt.GetOffset1(); // offset of subbuffer 1
```

_Originally posted by @atamazov in https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1324#issuecomment-985808818_

### PR DESCRIPTION
**Pull request by shaojiewang**
1. fix #1326 : abstract a class to hold the offsets and sizes of each sub buffer for transpose+asm_igemm solvers.
2. fix #1317 : fix mem fault on OCL BE
3. add some test case for transpose+asm_igemm solvers.

### CODE REVIEW

**Comment by shaojiewang** [comment]
@atamazov I can not run ctest on gfx90a at all. Could you help to check if some code work not properly?

**Comment by atamazov** [comment]
@shaojiewang Yes, as soon I do some other urgent work.

**Comment by junliume** [comment]
@atamazov @shaojiewang  should we include this into the next round of staging too? Is it related to 
[SWDEV-313026](https://ontrack-internal.amd.com/browse/SWDEV-313026) ?

**Review by atamazov — DISMISSED** [review]
This should remove WORKAROUND_ISSUE_1317 from #1321

**Comment by atamazov** [comment]
@junliume No, this is not needed in 5.0.

**Comment by shaojiewang** [comment]
> This should remove WORKAROUND_ISSUE_1317 from #1321

@atamazov The W/A macro was removed.

**Comment by atamazov** [comment]
Oops, looked into wrong diff.

File: src/conv/invokers/impl_gemm_dynamic.cpp [hunk 1]
```diff
@@ -541,6 +541,8 @@ InvokerFactory MakeImplGemmDynamicForwardXdlopsNHWCInvokerFactory(
     int trans_weight_idx = -1;
     int trans_output_idx = -1;
 
+    size_t buf_alignment = 256;
```
Comment (atamazov) [inline src/conv/invokers/impl_gemm_dynamic.cpp:544]:
```suggestion
    constexpr size_t buf_alignment = 256;
```

File: src/hip/batched_transpose_sol.cpp [hunk 2]
```diff
@@ -379,4 +379,32 @@ size_t BatchedTransposeSolution::GetSize() const
     return miopen::GetTypeSize(data_type) * batch * height * width;
 }
 
+TransposeSolutionWorkspaceBufTraits::TransposeSolutionWorkspaceBufTraits(std::initializer_list<size_t> v_size_,
```
Comment (atamazov) [inline src/hip/batched_transpose_sol.cpp:382]: Let's make it available for general use. Move this to buffer_info.hpp/cpp and rename to `MultiBufferWorkspaceTraits`. What do you think?

**Review by atamazov — CHANGES_REQUESTED** [review]
Almost good

**Comment by atamazov** [comment]
> @atamazov I can not run ctest on gfx90a with OCL BE at all. Could you please help to check if some code work not properly?

Testing started on MI200 node.

File: test/CMakeLists.txt [hunk 3]
```diff
@@ -1301,6 +1301,28 @@ COMMAND ${DYNAMIC_IMPLICITGEMM_XDLOPS_NHWC_FWD_ENVS} $<TARGET_FILE:test_conv2d>
 COMMAND ${DYNAMIC_IMPLICITGEMM_XDLOPS_NHWC_FWD_ENVS} $<TARGET_FILE:test_conv2d> ${MIOPEN_TEST_FLOAT_ARG} --verbose --input  16   3 17 17 --weights  64   3 1 1 --pads_strides_dilations 0 0 1 1 1 1 --disable-backward-data --disable-backward-weights --in_layout NHWC --fil_layout NHWC --out_layout NHWC
 COMMAND ${DYNAMIC_IMPLICITGEMM_XDLOPS_NHWC_FWD_ENVS} $<TARGET_FILE:test_conv2d> ${MIOPEN_TEST_FLOAT_ARG} --verbose --input   2  64 19 19 --weights 510  64 3 3 --pads_strides_dilations 1 1 1 1 1 1 --disable-backward-data --disable-backward-weights --in_layout NHWC --fil_layout NHWC --out_layout NHWC
 )
+
+add_custom_test(test_transpose_conv_igemm_dynamic_xdlops_nhwc_fwd SKIP_UNLESS_ALL HALF_ENABLED VEGA_DISABLED SKIP_XNACK_ON
```
Comment (atamazov) [inline test/CMakeLists.txt:1305]: Can we use something other than `transpose_conv`? This can be easily confused with transposed convolutions. Maybe, test_conv_igemm_dynamic_xdlops_nhwc_fwd\_\____nchw___ ? Ditto all other places.

**Review by atamazov — CHANGES_REQUESTED** [review]

**Comment by atamazov** [comment]
> Testing started on MI200 node.

Passed! :tada:

File: src/hip/batched_transpose_sol.cpp (hunk 2 above)
Comment (shaojiewang) [reply src/hip/batched_transpose_sol.cpp:382]: Agreed. I'll move it.

File: src/conv/invokers/impl_gemm_dynamic.cpp (hunk 1 above)
Comment (shaojiewang) [reply src/conv/invokers/impl_gemm_dynamic.cpp:544]: Thanks

File: test/CMakeLists.txt (hunk 3 above)
Comment (shaojiewang) [reply test/CMakeLists.txt:1305]: Yes. I'll rename them.

File: src/hip/batched_transpose_sol.cpp (hunk 2 above)
Comment (shaojiewang) [reply src/hip/batched_transpose_sol.cpp]: moved and renamed.

File: test/CMakeLists.txt (hunk 3 above)
Comment (shaojiewang) [reply test/CMakeLists.txt]: renamed

File: src/include/miopen/buffer_info.hpp [hunk 4]
```diff
@@ -307,6 +308,19 @@ struct WinogradBufferInfo
...
 };
 
+struct MultiBufferWorkspaceTraits
+{
+    MultiBufferWorkspaceTraits(std::initializer_list<size_t> v_size_, size_t alignment_);
+    size_t GetSize() const;
+    size_t GetOffset(size_t index) const;
+
+    size_t size;
+    int buffer_num;
```
Comment (atamazov) [inline src/include/miopen/buffer_info.hpp:318]: This member is not necessary

File: src/buffer_info.cpp [hunk 5]
```diff
@@ -148,4 +148,29 @@ BuffInfo::BuffInfo(MemLayout_t layout, int nk, int c, int h, int w, int g, int _
...
+    for(auto each_size : v_size)
+    {
+        size_t padding = (alignment - (each_size % alignment)) % alignment;
+        each_offset += each_size + padding;
+        v_offset.push_back(each_offset);
+    }
+    size = v_offset[buffer_num];
+}
+
+size_t MultiBufferWorkspaceTraits::GetSize() const { return size; }
```
Comment (atamazov) [inline src/buffer_info.cpp:167]: I recommend removing `size` from the class and returning `v_offset.back()`.

**Review by atamazov — DISMISSED** [review]

File: src/include/miopen/buffer_info.hpp (hunk 4 above)
Comment (shaojiewang) [reply src/include/miopen/buffer_info.hpp]: OK. removed.

File: src/buffer_info.cpp (hunk 5 above)
Comment (shaojiewang) [reply src/buffer_info.cpp]: Ok. changed.

**Comment by atamazov** [comment]
@JehandadKhan `need_find_db_update` because this increases required workspace size for the affected solvers.

**Review by atamazov — CHANGES_REQUESTED** [review]
This can't be merged as is due to #1349

**Comment by atamazov** [comment]
@shaojiewang #1352 (which extends WORKAROUND_ISSUE_1317 to tests) will be merged soon. This PR should revert it.

**Comment by shaojiewang** [comment]
> @shaojiewang #1352 (which extends WORKAROUND_ISSUE_1317 to tests) will be merged soon. This PR should revert it.

OK

**Comment by junliume** [comment]
@shaojiewang  tried to resolve conflict, please double check :)

**Comment by shaojiewang** [comment]
> 

Thanks a lot, I'll check very soon.

**Comment by shaojiewang** [comment]
> @shaojiewang tried to resolve conflict, please double check :)

Thanks a lot, I'll check very soon.

**Comment by shaojiewang** [comment]
@junliume error removed.
@atamazov #1352 is reverted.

**Comment by atamazov** [comment]
> This can't be merged as is due to #1349

#1349 is closed, so this can be merged now.

**Review by atamazov — APPROVED** [review]
LGTM

**Comment by atamazov** [comment]
@shaojiewang Please do not use hash sign in branch names anymore. It seems incompatible with some functions of GUI of our CI.

**Comment by shaojiewang** [comment]
> Please do not use hash sign in branch names anymore. It seems incompatible with some functions of GUI of our CI.

Yes, sure. Sorry for that.

**Comment by atamazov** [comment]
@shaojiewang 
> Yes, sure. Sorry for that.

No problem ;)
