### PR TITLE
Fix SQLite `std::logic_error`

### LINKED ISSUE #306: std::logic_error in SQLite deleter
In "near" develop TOT this test on gfx900 (haven't tested other ASICS):

`bin/test_conv2d --float --cmode conv --pmode default --group-count 1 --enable-fdb 1 --batch_size 1 --input_channels 32 --output_channels 32 --spatial_dim_elements 28 28 --filter_dims 1 1 --pads_strides_dilations 0 0 1 1 2 2 --trans_output_pads 0 0`

Causes:
```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)
dlowell@tengu:[reshuffleAndReduceTestCases]~/MIOpen/oclbuild$
```

Partial frames in GDB:
```
#2  0x00007ffff680f56c in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*> (this=0x7fffffffdcf0, __beg=0x0, __end=0xffffffffffffffff <error: Cannot access memory at address 0xffffffffffffffff>)
    at /usr/include/c++/7/bits/basic_string.tcc:212
212               std::__throw_logic_error(__N("basic_string::"
(gdb) list
207           _M_construct(_InIterator __beg, _InIterator __end,
208                        std::forward_iterator_tag)
209           {
210             // NB: Not required, but considered best practice.
211             if (__gnu_cxx::__is_null_pointer(__beg) && __beg != __end)
212               std::__throw_logic_error(__N("basic_string::"
213                                            "_M_construct null not valid"));
214
215             size_type __dnew = static_cast<size_type>(std::distance(__beg, __end));
216
(gdb) up
#3  0x00007ffff6ad9f63 in miopen::SQLite::impl::SQLiteCloser::operator() (this=0x555555e26720, ptr=0x555555d22128)
    at /home/dlowell/MIOpen/src/sqlite_db.cpp:59
59                  std::string filename_(sqlite3_db_filename(ptr, "main"));
(gdb)
#4  0x00007ffff6adb363 in std::unique_ptr<sqlite3, miopen::SQLite::impl::SQLiteCloser>::~unique_ptr (this=0x555555e26720,
    __in_chrg=<optimized out>) at /usr/include/c++/7/bits/unique_ptr.h:263
263               get_deleter()(__ptr);
(gdb) up
#5  0x00007ffff6add812 in miopen::SQLite::impl::~impl (this=0x555555e26720, __in_chrg=<optimized out>)
    at /home/dlowell/MIOpen/src/sqlite_db.cpp:53
53      class SQLite::impl
(gdb)
#6  0x00007ffff6add838 in std::default_delete<miopen::SQLite::impl>::operator() (this=0x555555d22650, __ptr=0x555555e26720)
    at /usr/include/c++/7/bits/unique_ptr.h:78
78              delete __ptr;
(gdb)
```

The actual branch I used was `reshuffleAndReduceTestCases`

Full backtrace attached below.
[bt1.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/4820509/bt1.txt)

### PR DESCRIPTION
**Pull request by JehandadKhan**
Resolves #306

### CODE REVIEW

File: src/sqlite_db.cpp [hunk 1]
```diff
@@ -56,7 +56,8 @@ class SQLite::impl
     {
         void operator()(sqlite3* ptr)
         {
-            std::string filename_(sqlite3_db_filename(ptr, "main"));
+            const auto c_filename = sqlite3_db_filename(ptr, "main");
+            std::string filename_((c_filename == nullptr) ? "" : c_filename);
```
Comment (daniellowell) [inline src/sqlite_db.cpp:60]: If it is a nullptr and it you handle it by passing an empty string why do you then try to close the file? Why not just skip that step?

Comment (JehandadKhan) [reply src/sqlite_db.cpp:60]: It might be an in memory database, if the pointer is already closed, `sqlite3_close` becomes a NOOP
