### PR TITLE
Fix the dynamic reduction GPU Memory Acccess failure with double on ROCM 4.3 

### LINKED ISSUE #1123: Dynamic reduction GPU access fault
GPU access fault when running on Vega20 (tested with MI-60) on ROCm4.3 HIP backend

```bin/test_reduce_test --all --double```

Error msg, when using HIP backend, and on ROCm4.3
```
bin/test_reduce_test --double --D 64 3 280 81 --R 0 2 --ReduceOp 4 --CompType 6 --N 1 --I 1 --scales 1 0
MIOpen(HIP): Info2 [AddKernel] Key: dynamic_generic_reduction "666_TUN_256_8_2_2_I4_RED0_2_BSIZE_256_1_P410"
MIOpen(HIP): Info2 [SystemCmd] cd /tmp/miopen-gridwise_generic_reduction_first_call_multiblock_reduce_partial_dims.cpp-a374-cf41-d2fa-6551;  /opt/rocm/llvm/bin/clang++  -std=c++17  --std=c++17 -DCK_AMD_GPU_GFX906 -DCK_USE_AMD_BUFFER_ATOMIC_FADD=0 -DCK_BLOCK_SYNC_LDS_WITHOUT_SYNC_VMEM=1 -DCK_USE_AMD_BUFFER_ADDRESSING=1 -DCK_PARAM_SRC_DATATYPE=6 -DCK_PARAM_DST_DATATYPE=6 -DCK_PARAM_REDUCE_COMPTYPE=6  -DCK_PARAM_BLOCKSIZE=256 -DCK_PARAM_THREAD_BUFFER_LENGTH=8 -DCK_PARAM_ACCESSES_PER_THREAD_INBLOCK=2 -DCK_PARAM_ACCESSES_PER_THREAD_INWARP=2 -DCK_PARAM_TOREDUCE_DIMS=0,2 -DCK_PARAM_INVARIANT_DIMS=1,3 -DCK_PARAM_REDUCE_OP=4 -DCK_PARAM_NAN_PROPAGATE=1 -DCK_PARAM_REDUCE_INDICES=1 -DCK_PARAM_IN_DIMS=4 -DCK_PARAM_OUT_DIMS=2 -DCK_PARAM_SRC2D_PADDING=1 -DCK_PARAM_DST1D_PADDING=0 -mcpu=gfx906 -Werror -Weverything -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-conversion -Wno-double-promotion -Wno-exit-time-destructors -Wno-extra-semi -Wno-float-conversion -Wno-gnu-anonymous-struct -Wno-gnu-zero-variadic-macro-arguments -Wno-missing-noreturn -Wno-missing-prototypes -Wno-nested-anon-types -Wno-padded -Wno-return-std-move-in-c++11 -Wno-shorten-64-to-32 -Wno-sign-conversion -Wno-unknown-warning-option -Wno-unused-command-line-argument -Wno-weak-vtables -Wno-covered-switch-default -Wno-disabled-macro-expansion -Wno-undefined-reinterpret-cast --cuda-gpu-arch=gfx906:xnack- --cuda-device-only -c -O3  -Wno-unused-command-line-argument -I. -mllvm -amdgpu-early-inline-all=true -mllvm -amdgpu-function-calls=false -xhip -isystem /opt/rocm-4.3.0/hip/../include -isystem /opt/rocm/llvm/lib/clang/13.0.0/include/.. -D__HIP_PLATFORM_HCC__=1 -D__HIP_PLATFORM_AMD__=1 -isystem /opt/rocm-4.3.0/hip/include -isystem /opt/rocm/include -L"/opt/rocm/llvm/lib/clang/13.0.0/include/../lib/linux" -lclang_rt.builtins-x86_64 --hip-link -L"/opt/rocm/llvm/lib/clang/13.0.0/include/../lib/linux" -lclang_rt.builtins-x86_64 -mllvm --amdgpu-spill-vgpr-to-agpr=0 -DHIP_PACKAGE_VERSION_FLAT=4003021300 gridwise_generic_reduction_first_call_multiblock_reduce_partial_dims.cpp -o /tmp/miopen-gridwise_generic_reduction_first_call_multiblock_reduce_partial_dims.cpp-a374-cf41-d2fa-6551/gridwise_generic_reduction_first_call_multiblock_reduce_partial_dims.cpp.o
MIOpen(HIP): Info2 [Log] Kernel gridwise_generic_reduction_first_call_multiblock_reduce_partial_dims.cpp Compile Time, ms: 3296.71
MIOpen(HIP): Info2 [AddKernel] Key: dynamic_generic_reduction "666_TUN_256_8_2_2_I4_RED0_2_BSIZE_256_1410"
Memory access fault by GPU node-5 (Agent handle: 0xafad50) on address 0x7f8c80a00000. Reason: Page not present or supervisor privilege.
```

Note
* It doesn't fail if dynamic reduction is disabled
* It doesn't fail if using OpenCL backend
* It doesn't fail if running a single config
* It doesn't fail if using ROCm4.1

### PR DESCRIPTION
**Pull request by qianfengz**
Resolves #1123 (pls. see explanation [here](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1123#issuecomment-909057168)).

The issue has been reproduced with ROCM 4.3 on both MI100 and MI25. 

This fix has passed the testing with ROCM 4.2/ROCM 4.3/ROCM 4.3.1 on either MI100 or MI25.

### CODE REVIEW

File: src/reducetensor.cpp [hunk 1]
```diff
@@ -62,11 +61,7 @@ namespace detail {
 
 static bool IsDynamicReductionEnabled()
```
Comment (asroy) [inline src/reducetensor.cpp:62]: Please just remove this function, which is introduced in workaround PR

File: src/reducetensor.cpp [hunk 2]
```diff
@@ -568,10 +563,13 @@ void ReduceTensorDescriptor::ReduceTensor(const Handle& handle,
...
     {
-        std::size_t aTypeSize = detail::GetDataTypeSize(aDesc.GetType());
+        std::size_t aTypeSize     = detail::GetDataTypeSize(aDesc.GetType());
+        auto ws_buf12_sizeInBytes = detail::IsDynamicReductionEnabled()
+                                        ? workspaceSizeInBytes - 4096
+                                        : workspaceSizeInBytes;
 
         long byteOffset =
-            static_cast<long>((workspaceSizeInBytes / (aTypeSize + sizeof(int))) * aTypeSize);
+            static_cast<long>((ws_buf12_sizeInBytes / (aTypeSize + sizeof(int))) * aTypeSize);
```
Comment (asroy) [inline src/reducetensor.cpp:572]: If I read your kernel correctly, the kernel is not packing a tensor value with its index in memory. So this way of calculating offset for index buffer is dangerous because you are assuming the data will be packed in memory byte-by-byte.


Please calculate ```byteOffset ``` for index buffer by properly calculating the buffer size for partial reduction output

**Review by asroy — DISMISSED** [review]

File: src/reducetensor.cpp (hunk 2 above)
Comment (qianfengz) [reply src/reducetensor.cpp:572]: workspaceSizeInBytes is the the user allocated bytes size, it should be no less than the actual required size,  and it could be obviously bigger than the required size.   So my calculation is based on this this allocated size.  No need to worry,  I added some gap when calculating the required size, and the index buffer is aligned in 64-byte boundary.  This logic is shared by both static and dynamic reduction,  had better not be changed

File: src/reducetensor.cpp (hunk 1 above)
Comment (qianfengz) [reply src/reducetensor.cpp]: Removed

File: src/reducetensor.cpp (hunk 2 above)
Comment (qianfengz) [reply src/reducetensor.cpp]: Change!

**Comment by qianfengz** [comment]
There is some problem with the CI

**Comment by shaojiewang** [comment]
> There is some problem with the CI

Maybe you could restart the test.

**Comment by qianfengz** [comment]
Luckily, the CI just passed

**Comment by atamazov** [comment]
After ~15 retries... awesome :/

File: src/reducetensor.cpp (hunk 1 above)
Comment (atamazov) [reply src/reducetensor.cpp]: [Note] I'd rather keep it (since it costs nothing, but gives some flexibility that might be useful in the future), but okay.

**Review by atamazov — APPROVED** [review]
LGTM!

So it was a problem in MIOpen, not in ROCm 4.3?

**Comment by atamazov** [comment]
@qianfengz No answer required, I see the explanation at https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1123#issuecomment-909057168

**Review by junliume — APPROVED** [review]
