### PR TITLE
[HOTFIX][tests] Limit applicability of ConvFwdBiasActivAPI/ConvFwdBiasResAddActivTest.ConvFusedAPI

### LINKED ISSUE #2633: [Tests] Tests fail on gfx1030 for Fused solver for Fwd Convolution with Residual add, Bias add and then activation function (#2517)
After #2517 
Navi21, ROCm 6.0, develop 2b9d9cdbb4b18a5bcec5603b6dfc9f3a7b58b6c7, **_"No supported fusion solvers found"_**, make check fails:
```bash
 833/1799 Test  #835: ConvFwdBiasActivAPI/ConvFwdBiasResAddActivTest.ConvFusedAPI/(5,  G:1 N:1 C:4 D:14 H:11 W:1 k:4 z:3 y:3 x:3 pad_z:1 pad_y:1 pad_x:1 stride_z:1 stride_y:1 stride_x:1 dilation_z:1 dilation_y:1 dilation_x:1 conv_mode:0, 1, 1, 8) ........................................................................................................................................................................................***Failed    3.48 sec
Running main() from /opt/rocm/cget/build/tmp-c4f1a42bcee536579a1248d25169f834201170c187fc6d80e8c510a7d28f6f48/googletest-1.14.0/googletest/src/gtest_main.cc
Note: Google Test filter = ConvFwdBiasActivAPI/ConvFwdBiasResAddActivTest.ConvFusedAPI/0
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from ConvFwdBiasActivAPI/ConvFwdBiasResAddActivTest
[ RUN      ] ConvFwdBiasActivAPI/ConvFwdBiasResAddActivTest.ConvFusedAPI/0
MIOpen(HIP): Info [GetFindModeValueImpl] MIOPEN_FIND_MODE = DYNAMIC_HYBRID(5)
PRNG seed: 12345678
MIOpen(HIP): Info [get_device_name] Raw device name: gfx1030
MIOpen(HIP): Info [Handle] stream: 0x2654620, device_id: 0
MIOpen(HIP): Info [AmdRocmMetadataVersionDetect] ROCm MD version AMDHSA_COv3, HIP version 6.0.23494, MIOpen version 3.1.0.2b9d9cdbb
MIOpen(HIP): Info [Measure] RamDb::Prefetch time: 0.037761 ms
MIOpen(HIP): Info [TryLoad] Find-db regenerating.
MIOpen(HIP): Info [AllocateBuffersAndMakeFusionInvokeParams] bias addr: 0x7f1f09a05000, size: 8
MIOpen(HIP): Info [AllocateBuffersAndMakeFusionInvokeParams] weight addr: 0x7f1f09a06000, size: 864
MIOpen(HIP): Info [AllocateBuffersAndMakeFusionInvokeParams] in addr: 0x7f1f09a08000, size: 1232
MIOpen(HIP): Info [AllocateBuffersAndMakeFusionInvokeParams] out addr: 0x7f1f09a09000, size: 1232
MIOpen(HIP): Info [GetPerfDbPathFile] Found exact perf database file
MIOpen(HIP): Info [Compile] No supported fusion solvers found
...
/root/github/MLOpen1/test/gtest/fused_conv_bias_res_add_activ.cpp:185: Failure
Expected equality of these values:
  status
    Which is: 8
  miopenStatusSuccess
    Which is: 0

MIOpen(HIP): Info [PrintVersion] HIPRTC v.9.0
/root/github/MLOpen1/test/gtest/fused_conv_bias_res_add_activ.cpp:130: Failure
Value of: error < threshold
  Actual: false
Expected: true
Error beyond tolerance Error:nan,  Threshold: 0.078125

[  FAILED  ] ConvFwdBiasActivAPI/ConvFwdBiasResAddActivTest.ConvFusedAPI/0, where GetParam() = (5,  G:1 N:1 C:4 D:14 H:11 W:1 k:4 z:3 y:3 x:3 pad_z:1 pad_y:1 pad_x:1 stride_z:1 stride_y:1 stride_x:1 dilation_z:1 dilation_y:1 dilation_x:1 conv_mode:0, 1, 1, 8) (3367 ms)
```

_Originally posted by @atamazov in https://github.com/ROCm/MIOpen/issues/2517#issuecomment-1867044254_

### PR DESCRIPTION
**Pull request by atamazov**
Resolves #2633 + more fixes for the test (e.g. makes it compliant to #1843).

----
[Attribution] @junliume @JehandadKhan
- https://github.com/ROCm/MIOpen/labels/bug
- https://github.com/ROCm/MIOpen/labels/testing
- https://github.com/ROCm/MIOpen/labels/urgency_blocker
- Proposed reviewers:
  - @JehandadKhan
  - @junliume
  - @amberhassaan

### CODE REVIEW

**Comment by junliume** [comment]
@atamazov CI pipeline started for this PR :)

**Comment by junliume** [comment]
Tested on `gfx1100` platform that both this one and #2634 resolves #2633, but this is a better one.

**Review by junliume — APPROVED** [review]

**Comment by atamazov** [comment]
@amberhassaan Despite the fact that this PR has already been merged in, it would be nice if you review it.

File: test/gtest/fused_conv_bias_res_add_activ.cpp [hunk 1]
```diff
@@ -25,14 +25,44 @@
...
+    return
+#if WORAROUND_ISSUE_2533
+        miopen::solver::ck_utility::is_ck_whitelist(get_handle().GetDeviceName()) //
+#else
+    /// \todo Check against specific ASCIs.
+#endif
+        && (float_arg == "--half" // So far only test for fp16 is implemented.
+            || float_arg.empty()) // Empty when gtest is run without parameters.
+        && !miopen::IsDisabled(
+               ENV(MIOPEN_TEST_ALL)); // Not disabled when gtest is run without parameters.
```
Comment (amberhassaan) [inline test/gtest/fused_conv_bias_res_add_activ.cpp:60]: I would like to remove this dependence on environment variables like `MIOPEN_TEST_ALL` or `MIOPEN_TEST_FLOAT_ARG` for new tests. All new tests should have unit tests methods for all the supported types. 

CC: @JehandadKhan , @junliume

File: test/gtest/fused_conv_bias_res_add_activ.cpp [hunk 2]
```diff
@@ -25,14 +25,44 @@
...
 
 #include "tensor_util.hpp"
 #include "get_handle.hpp"
 
 #include "conv3d_test_case.hpp"
 
+MIOPEN_DECLARE_ENV_VAR_BOOL(MIOPEN_TEST_ALL)
+MIOPEN_DECLARE_ENV_VAR_STR(MIOPEN_TEST_FLOAT_ARG)
+
+#if MIOPEN_USE_COMPOSABLEKERNEL
```
Comment (amberhassaan) [inline test/gtest/fused_conv_bias_res_add_activ.cpp:41]: This switch does not seem useful given how we rely heavily on CK and that we don't have (to my knowledge) alternatives to CK that intend to replace it. Do we expect to ship/deploy MIOpen in a setting where CK is absent or does not work? 

CC: @JehandadKhan , @junliume

**Review by amberhassaan — COMMENTED** [review]
Post merge comments and questions.

File: test/gtest/fused_conv_bias_res_add_activ.cpp (hunk 1 above)
Comment (atamazov) [reply test/gtest/fused_conv_bias_res_add_activ.cpp:60]: This is for CI stage 'Fp32 Hip Debug NOCK AnyGPU Build-Only' to pass.

File: test/gtest/fused_conv_bias_res_add_activ.cpp (hunk 2 above)
Comment (atamazov) [reply test/gtest/fused_conv_bias_res_add_activ.cpp:41]: @amberhassaan This is for CI stage 'Fp32 Hip Debug NOCK AnyGPU Build-Only' to pass.

File: test/gtest/fused_conv_bias_res_add_activ.cpp (hunk 1 above)
Comment (atamazov) [reply test/gtest/fused_conv_bias_res_add_activ.cpp:60]: @amberhassaan I'm second to this. We will remove this when possible. However, for now we need to handle `MIOPEN_TEST_FLOAT_ARG` to support the existing Jenkinsfile, which distributes testing of different datatypes on different nodes (for the sake of faster CI turnaround). See #1843.

Ditto `MIOPEN_TEST_ALL` because we still want to have smoke tests in our CI.
