### PR TITLE
MIOpenDriver: exit with status 1 on usage error

### LINKED ISSUE #436: [MIOpen] MIOpenDriver not exiting with failing status in all cases.
@scottt

### PR DESCRIPTION
**Pull request by stellaraccident**
This makes inspecting MIOpenDriver exit status after light manual testing easier.

Fixes https://github.com/ROCm/TheRock/issues/436

### CODE REVIEW

**Review by BrianHarrisonAMD — APPROVED** [review]

File: driver/driver.hpp [hunk 1]
```diff
@@ -403,10 +403,10 @@ inline std::string ParseBaseArg(int argc, char* argv[])
        arg != "--version")
     {
         printf("FAILED: Invalid Base Input Argument\n");
-        Usage();
+        Usage(1);
     }
     else if(arg == "-h" || arg == "--help" || arg == "-?")
-        Usage();
+        Usage(0);
```
Comment (averinevg) [inline driver/driver.hpp]:
```suggestion
        Usage(EXIT_SUCCESS);
```

File: driver/driver.hpp [hunk 2]
```diff
@@ -363,15 +363,15 @@ inline void PadBufferSize(size_t& sz, int datatype_sz)
...
+    exit(e); // NOLINT (concurrency-mt-unsafe)
 }
 
 inline std::string ParseBaseArg(int argc, char* argv[])
 {
     if(argc < 2)
     {
         printf("FAILED: Invalid Number of Input Arguments\n");
-        Usage();
+        Usage(1);
```
Comment (averinevg) [inline driver/driver.hpp]:
```suggestion
        Usage(EXIT_FAILURE);
```

File: driver/driver.hpp [hunk 3]
```diff
@@ -403,10 +403,10 @@ inline std::string ParseBaseArg(int argc, char* argv[])
        arg != "--version")
     {
         printf("FAILED: Invalid Base Input Argument\n");
-        Usage();
+        Usage(1);
```
Comment (averinevg) [inline driver/driver.hpp]:
```suggestion
        Usage(EXIT_FAILURE);
```

File: driver/tensorop_driver.hpp [hunk 4]
```diff
@@ -184,8 +184,7 @@ int TensorOpDriver<Tgpu, Tref>::SetTensorOpFromCmdLineArgs()
             op = static_cast<miopenTensorOp_t>(raw_op - 2);
         else
         {
-            Usage();
-            exit(-1); // NOLINT (concurrency-mt-unsafe)
+            Usage(1);
```
Comment (averinevg) [inline driver/tensorop_driver.hpp]:
```suggestion
            Usage(EXIT_FAILURE);
```

**Review by BrianHarrisonAMD — APPROVED** [review]

**Review by BradPepersAMD — APPROVED** [review]
