### PR TITLE
Disable Op2dTensorLite kernel for the cases with wrong results

### LINKED ISSUE #2314: Op2dTensorLite doesn't handle the last element in some cases (OpTensor3d test failed)
When we reach number of workgroups hard limit (`int max_num_wg  = 4096;`) Op2dTensorLite stops to handle all the elements beyond total threads limit (4096*256 = 1048576):

./bin/test_tensor_ops --float --a 1 1 1048577 --b 1 1 1048577 --sa 1 1 1 --sb 1 1 1 --sc 1 1 1 --offsets 0 0 0 --alpha-beta 1 1 1 --packed 1
```
...
MIOpen(HIP): Info2 [Log] Kernel MIOpenTensorKernels.cl Compile Time, ms: 208.425
MIOpen(HIP): Info2 [run] kernel_name = Op2dTensorLite, global_work_dim = { 1048576, 64, 1 }, local_work_dim = { 256, 1, 1 }
...
c[1048576](16.000000) = a[1048576](16.000000) * b[1048576](16.000000)
...
Mismatch at 1048576: 272 != 16
```

When I set `max_num_wg` limit to 16, I encountered this error much earlier, at the elements beyond 4096.

This kernel is widely used in RNN and we were just lucky that there were small tensors.

### PR DESCRIPTION
**Pull request by CAHEK7**
Fix for #2314 

Since we do not support OpenCL kernel, it just disables Op2dTensorLite for the cases where it produces wrong results.
There is also a ticket (#2221) for tensor operations improvements, any further fixes or perf improvements will be done under #2221.

Potentially it may affect RNN, but as far as I know, it uses small enough tensors to fit this limitation.

### CODE REVIEW

**Review by muralinr — COMMENTED** [review]
Tensor operations kernels are used by RNNs (LSTM) currently. Can you please run these config tests?

./bin/MIOpenDriver rnnfp16 -n 224 -W 224 -H 1000 -l 8 -b 1 -m lstm -p 0 -r 0 -k 32 -F 2 -t 1 -w 1
./bin/MIOpenDriver rnnfp16 -n 224 -W 224 -H 1000 -l 8 -b 1 -m lstm -p 0 -r 0 -k 32 -F 4 -t 1 -w 1
./bin/MIOpenDriver rnnfp16 -n 224 -W 224 -H 1000 -l 8 -b 1 -m lstm -p 0 -r 0 -k 32 -c 0 -F 1 -t 1 -w 1

**Comment by CAHEK7** [comment]
@muralinr  I've tried all that examples - one has failed regardless of my changes.
1) they use quite small tensors and can't be affected by this particular bug
2) CI has at least a couple of RNN cases where tensor operations are used and everything has passed
3) the tests are incredibly slow comparing to the experiments in #1491 

```
root@Hongkong-Ubu20:/home/user/bld# ./bin/MIOpenDriver rnnfp16 -n 224 -W 224 -H 1000 -l 8 -b 1 -m lstm -p 0 -r 0 -k 32 -F 2 -t 1 -w 1
MIOpen(HIP): Info [get_device_name] Raw device name: gfx1030
GPU Kernel Time Backward Data RNN Elapsed: 642.247314 ms
Wall-clock Time Backward Data RNN Elapsed: 642.364502 ms
length of data sequence == 1 is short than time sequence == 32, padding the rest of data sequence with 224
length of data sequence == 1 is short than time sequence == 32, padding the rest of data sequence with 224
verify lstm bwddata
Backward RNN Data FAILED: 0.0563593
difference at inital hidden state FAILED: 0.0797751
difference at inital cell state FAILED: 0.187254

root@Hongkong-Ubu20:/home/user/bld# ./bin/MIOpenDriver rnnfp16 -n 224 -W 224 -H 1000 -l 8 -b 1 -m lstm -p 0 -r 0 -k 32 -F 4 -t 1 -w 1                       MIOpen(HIP): Info [get_device_name] Raw device name: gfx1030
GPU Kernel Time Backward Weights RNN Elapsed: 494.112671 ms // it is just an 11.397395 ms in PR #1491
Wall-clock Time Backward Weights RNN Elapsed: 494.249603 ms
length of data sequence == 1 is short than time sequence == 32, padding the rest of data sequence with 224
length of data sequence == 1 is short than time sequence == 32, padding the rest of data sequence with 224
verify lstm bwdwei
Backward RNN Weights Verifies on CPU and GPU

root@Hongkong-Ubu20:/home/user/bld# ./bin/MIOpenDriver rnnfp16 -n 224 -W 224 -H 1000 -l 8 -b 1 -m lstm -p 0 -r 0 -k 32 -c 0 -F 1 -t 1 -w 1                  MIOpen(HIP): Info [get_device_name] Raw device name: gfx1030
GPU Kernel Time Forward RNN Elapsed: 0.000000 ms
Wall-clock Time Forward RNN Elapsed: 559.686401 ms
length of data sequence == 1 is short than time sequence == 32, padding the rest of data sequence with 224
length of data sequence == 1 is short than time sequence == 32, padding the rest of data sequence with 224
verify lstm fwd
final hidden Verifies on CPU and GPU
final cell Verifies on CPU and GPU
```

**Comment by muralinr** [comment]
> ./bin/MIOpenDriver rnnfp16 -n 224 -W 224 -H 1000 -l 8 -b 1 -m lstm -p 0 -r 0 -k 32 -F 2 -t 1 -w 1

Thanks @CAHEK7. I approve this PR.

**Review by muralinr — APPROVED** [review]

File: src/ocl/tensorocl.cpp [hunk 1]
```diff
@@ -185,8 +185,18 @@ void OpTensor3d(const Handle& handle,
 
     size_t total_work = std::max(clens[2] / RD_BLCK, size_t(1));
     size_t grp_sz     = (total_work + local_threads - 1) / local_threads;
-    grp_sz            = std::min(size_t(max_num_wg), grp_sz);
-    size_t glb_sz     = local_threads * grp_sz;
+
+    // opencl kernels are no longer supported, fallback to generic case
+    bool lite_applicable = grp_sz <= size_t(max_num_wg);
```
Comment (shurale-nkn) [inline src/ocl/tensorocl.cpp:190]: const std::vector<size_t> vgd1{glb_sz, glb_sz2, 1};

workgroup size is multiplication of glb_sz and glb_sz2, so why limited to 4096? 
The maximum Grid size can be up to 4294967295

**Review by shurale-nkn — DISMISSED** [review]

File: src/ocl/tensorocl.cpp (hunk 1 above)
Comment (CAHEK7) [reply src/ocl/tensorocl.cpp:190]: I have no ideas, for me that value doesn't make much sense. It's a legacy code and I decided not to touch it right now and just kept all the other non-broken behavior exactly the same.

If there are no objections, it can be limited to the maximum grid size, but it may affect perf metrics.
Also I'm going to update this part of code at some point, so probably I'll get rid of this limit.

Comment (CAHEK7) [reply src/ocl/tensorocl.cpp:190]: @shurale-nkn 
As for this particular limit - proper fix must be done on the kernel side by applying one more loop. But since we do not develop ocl kernel anymore and I do not want to gather perf metrics just for no reason, I insist to keep everything as it is and just fallback to the generic case for the broken kernel.

All the performance improvements will be done under #2221 and if you have any ideas\suggestions - you a welcome to that ticket.

**Comment by CAHEK7** [comment]
@shurale-nkn if you think that increasing number of groups won't affect anything, I agree and just remove this limit. If it may potentially affect anything and it may require additional testing and performance measurements - for me it's better to avoid such changes and focus on overall performance improvements.
@junliume what do you think?

**Review by junliume — APPROVED** [review]

File: src/ocl/tensorocl.cpp (hunk 1 above)
Comment (junliume) [reply src/ocl/tensorocl.cpp:190]: Yep I will keep the legacy OCL not changed until proven otherwise.

**Comment by yanjianglu** [comment]
> @muralinr I've tried all that examples - one has failed regardless of my changes.
> 
> 1. they use quite small tensors and can't be affected by this particular bug
> 2. CI has at least a couple of RNN cases where tensor operations are used and everything has passed
> 3. the tests are incredibly slow comparing to the experiments in [[RNN][Op2dTensorSquash] Tensor squash kernel optimizations #1491](https://github.com/ROCm/MIOpen/pull/1491)
> 
> ```
> root@Hongkong-Ubu20:/home/user/bld# ./bin/MIOpenDriver rnnfp16 -n 224 -W 224 -H 1000 -l 8 -b 1 -m lstm -p 0 -r 0 -k 32 -F 2 -t 1 -w 1
> MIOpen(HIP): Info [get_device_name] Raw device name: gfx1030
> GPU Kernel Time Backward Data RNN Elapsed: 642.247314 ms
> Wall-clock Time Backward Data RNN Elapsed: 642.364502 ms
> length of data sequence == 1 is short than time sequence == 32, padding the rest of data sequence with 224
> length of data sequence == 1 is short than time sequence == 32, padding the rest of data sequence with 224
> verify lstm bwddata
> Backward RNN Data FAILED: 0.0563593
> difference at inital hidden state FAILED: 0.0797751
> difference at inital cell state FAILED: 0.187254
> 
> root@Hongkong-Ubu20:/home/user/bld# ./bin/MIOpenDriver rnnfp16 -n 224 -W 224 -H 1000 -l 8 -b 1 -m lstm -p 0 -r 0 -k 32 -F 4 -t 1 -w 1                       MIOpen(HIP): Info [get_device_name] Raw device name: gfx1030
> GPU Kernel Time Backward Weights RNN Elapsed: 494.112671 ms // it is just an 11.397395 ms in PR #1491
> Wall-clock Time Backward Weights RNN Elapsed: 494.249603 ms
> length of data sequence == 1 is short than time sequence == 32, padding the rest of data sequence with 224
> length of data sequence == 1 is short than time sequence == 32, padding the rest of data sequence with 224
> verify lstm bwdwei
> Backward RNN Weights Verifies on CPU and GPU
> 
> root@Hongkong-Ubu20:/home/user/bld# ./bin/MIOpenDriver rnnfp16 -n 224 -W 224 -H 1000 -l 8 -b 1 -m lstm -p 0 -r 0 -k 32 -c 0 -F 1 -t 1 -w 1                  MIOpen(HIP): Info [get_device_name] Raw device name: gfx1030
> GPU Kernel Time Forward RNN Elapsed: 0.000000 ms
> Wall-clock Time Forward RNN Elapsed: 559.686401 ms
> length of data sequence == 1 is short than time sequence == 32, padding the rest of data sequence with 224
> length of data sequence == 1 is short than time sequence == 32, padding the rest of data sequence with 224
> verify lstm fwd
> final hidden Verifies on CPU and GPU
> final cell Verifies on CPU and GPU
> ```
MIOpenDriver rnnfp16  use -F 2 params，Always failed！Is it because LSTM cannot independently verify backpropagation?

**Comment by shurale-nkn** [comment]
> > @muralinr I've tried all that examples - one has failed regardless of my changes.
> > 
> > 1. they use quite small tensors and can't be affected by this particular bug
> > 2. CI has at least a couple of RNN cases where tensor operations are used and everything has passed
> > 3. the tests are incredibly slow comparing to the experiments in [[RNN][Op2dTensorSquash] Tensor squash kernel optimizations #1491](https://github.com/ROCm/MIOpen/pull/1491)
> > 
> > ```
> > root@Hongkong-Ubu20:/home/user/bld# ./bin/MIOpenDriver rnnfp16 -n 224 -W 224 -H 1000 -l 8 -b 1 -m lstm -p 0 -r 0 -k 32 -F 2 -t 1 -w 1
> > MIOpen(HIP): Info [get_device_name] Raw device name: gfx1030
> > GPU Kernel Time Backward Data RNN Elapsed: 642.247314 ms
> > Wall-clock Time Backward Data RNN Elapsed: 642.364502 ms
> > length of data sequence == 1 is short than time sequence == 32, padding the rest of data sequence with 224
> > length of data sequence == 1 is short than time sequence == 32, padding the rest of data sequence with 224
> > verify lstm bwddata
> > Backward RNN Data FAILED: 0.0563593
> > difference at inital hidden state FAILED: 0.0797751
> > difference at inital cell state FAILED: 0.187254
> > 
> > root@Hongkong-Ubu20:/home/user/bld# ./bin/MIOpenDriver rnnfp16 -n 224 -W 224 -H 1000 -l 8 -b 1 -m lstm -p 0 -r 0 -k 32 -F 4 -t 1 -w 1                       MIOpen(HIP): Info [get_device_name] Raw device name: gfx1030
> > GPU Kernel Time Backward Weights RNN Elapsed: 494.112671 ms // it is just an 11.397395 ms in PR #1491
> > Wall-clock Time Backward Weights RNN Elapsed: 494.249603 ms
> > length of data sequence == 1 is short than time sequence == 32, padding the rest of data sequence with 224
> > length of data sequence == 1 is short than time sequence == 32, padding the rest of data sequence with 224
> > verify lstm bwdwei
> > Backward RNN Weights Verifies on CPU and GPU
> > 
> > root@Hongkong-Ubu20:/home/user/bld# ./bin/MIOpenDriver rnnfp16 -n 224 -W 224 -H 1000 -l 8 -b 1 -m lstm -p 0 -r 0 -k 32 -c 0 -F 1 -t 1 -w 1                  MIOpen(HIP): Info [get_device_name] Raw device name: gfx1030
> > GPU Kernel Time Forward RNN Elapsed: 0.000000 ms
> > Wall-clock Time Forward RNN Elapsed: 559.686401 ms
> > length of data sequence == 1 is short than time sequence == 32, padding the rest of data sequence with 224
> > length of data sequence == 1 is short than time sequence == 32, padding the rest of data sequence with 224
> > verify lstm fwd
> > final hidden Verifies on CPU and GPU
> > final cell Verifies on CPU and GPU
> > ```
> 
> MIOpenDriver rnnfp16 use -F 2 params，Always failed！Is it because LSTM cannot independently verify backpropagation?

Yes, the previous steps are always needed for the backward. allowed -F 0,  -F1, -F3, -F7
